package Algorithm;

import javabean.Answer;
import javabean.StuAnswer;

import java.util.ArrayList;
import java.util.List;

class TotalScoreTest {
    @org.junit.jupiter.api.Test
    void computerscore(){
        StuAnswer stuAnswer1=new StuAnswer(1,"A","A");
        StuAnswer stuAnswer2=new StuAnswer(2,"A","B");
        StuAnswer stuAnswer3=new StuAnswer(3,"A","C");
        StuAnswer stuAnswer4=new StuAnswer(4,"A","D");
        StuAnswer stuAnswer5=new StuAnswer(5,"A","A");
        StuAnswer stuAnswer6=new StuAnswer(6,"A","A");
        StuAnswer stuAnswer7=new StuAnswer(7,"A","A");
        StuAnswer stuAnswer8=new StuAnswer(8,"A","A");
        StuAnswer stuAnswer9=new StuAnswer(9,"A","A");
        StuAnswer stuAnswer10=new StuAnswer(10,"A","A");
        StuAnswer stuAnswer11=new StuAnswer(11,"A","T");
        StuAnswer stuAnswer12=new StuAnswer(12,"A","T");
        StuAnswer stuAnswer13=new StuAnswer(13,"A","F");
        StuAnswer stuAnswer14=new StuAnswer(14,"A","F");
        StuAnswer stuAnswer15=new StuAnswer(15,"A","T");
        StuAnswer stuAnswer16=new StuAnswer(16,"A","F");
        StuAnswer stuAnswer17=new StuAnswer(17,"A","T");
        StuAnswer stuAnswer18=new StuAnswer(18,"A","F");
        StuAnswer stuAnswer19=new StuAnswer(19,"A","T");
        StuAnswer stuAnswer20=new StuAnswer(20,"A","T");
        StuAnswer stuAnswer21=new StuAnswer(21,"A","T");
        StuAnswer stuAnswer22=new StuAnswer(22,"A","控制器");
        StuAnswer stuAnswer23=new StuAnswer(23,"A","输入");
        StuAnswer stuAnswer24=new StuAnswer(24,"A","输出");
        StuAnswer stuAnswer25=new StuAnswer(25,"A","存储器");
        StuAnswer stuAnswer26=new StuAnswer(26,"A","输出");
        StuAnswer stuAnswer27=new StuAnswer(27,"A","输入");
        StuAnswer stuAnswer28=new StuAnswer(28,"A","输出");
        StuAnswer stuAnswer29=new StuAnswer(29,"A","输入");
        StuAnswer stuAnswer30=new StuAnswer(30,"A","存储");
        StuAnswer stuAnswer31=new StuAnswer(31,"A","软件工程是：将系统化的方法应用于软件的开发、运行，即将工程化应用于软件");
        StuAnswer stuAnswer32=new StuAnswer(32,"A","定义阶段：可行性研究初步项目计划、详细设计、实现、测试；运行和维护阶段：运行、维护、废弃");
        StuAnswer stuAnswer33=new StuAnswer(33,"A","原则：1、抽象；2、信息隐蔽；3、模块化；4、局部化；5、确定性");
        StuAnswer stuAnswer34=new StuAnswer(34,"A","用分阶段的生存周期管理");
        StuAnswer stuAnswer35=new StuAnswer(35,"A","坚持进行阶段评审");
        Answer answer1=new Answer(1,"A","A","2");
        Answer answer2=new Answer(2,"A","A","2");
        Answer answer3=new Answer(3,"A","A","2");
        Answer answer4=new Answer(4,"A","A","2");
        Answer answer5=new Answer(5,"A","A","2");
        Answer answer6=new Answer(6,"A","A","2");
        Answer answer7=new Answer(7,"A","A","2");
        Answer answer8=new Answer(8,"A","A","2");
        Answer answer9=new Answer(9,"A","A","2");
        Answer answer10=new Answer(10,"A","A","2");
        Answer answer11=new Answer(11,"A","T","2");
        Answer answer12=new Answer(12,"A","T","2");
        Answer answer13=new Answer(13,"A","T","2");
        Answer answer14=new Answer(14,"A","T","2");
        Answer answer15=new Answer(15,"A","T","2");
        Answer answer16=new Answer(16,"A","T","2");
        Answer answer17=new Answer(17,"A","T","2");
        Answer answer18=new Answer(18,"A","T","2");
        Answer answer19=new Answer(19,"A","T","2");
        Answer answer20=new Answer(20,"A","T","2");
        Answer answer21=new Answer(21,"A","控制器","2");
        Answer answer22=new Answer(22,"A","输入","2");
        Answer answer23=new Answer(23,"A","输入","2");
        Answer answer24=new Answer(24,"A","输出","2");
        Answer answer25=new Answer(25,"A","运算","2");
        Answer answer26=new Answer(26,"A","控制","2");
        Answer answer27=new Answer(27,"A","存储器","2");
        Answer answer28=new Answer(28,"A","输出","2");
        Answer answer29=new Answer(29,"A","输入","2");
        Answer answer30=new Answer(30,"A","存储","2");
        Answer answer31=new Answer(31,"A","软件工程是：1.将系统化的、严格约束的、可量化的方法应用于软件的开发、运行和维护，即将工程化应用于软件","8");
        Answer answer32=new Answer(32,"A","定义阶段：可行性研究初步项目计划、需求分析；开发阶段：概要设计、详细设计、实现、测试；运行和维护阶段：运行、维护、废弃","8");
        Answer answer33=new Answer(33,"A","原则：1、抽象；2、信息隐蔽；3、模块化；4、局部化；5、确定性；6，一致性；7、完备性；8、可验证性","8");
        Answer answer34=new Answer(34,"A","用分阶段的生存周期计划进行严格的管理","8");
        Answer answer35=new Answer(35,"A","坚持进行阶段评审","8");

        List<StuAnswer> stuAnswers=new ArrayList<StuAnswer>();
        List<Answer> answers=new ArrayList<Answer>() ;
        stuAnswers.add(stuAnswer1);
        stuAnswers.add(stuAnswer2);
        stuAnswers.add(stuAnswer3);
        stuAnswers.add(stuAnswer4);
        stuAnswers.add(stuAnswer5);
        stuAnswers.add(stuAnswer6);
        stuAnswers.add(stuAnswer7);
        stuAnswers.add(stuAnswer8);
        stuAnswers.add(stuAnswer9);
        stuAnswers.add(stuAnswer10);
        stuAnswers.add(stuAnswer11);
        stuAnswers.add(stuAnswer12);
        stuAnswers.add(stuAnswer13);
        stuAnswers.add(stuAnswer14);
        stuAnswers.add(stuAnswer15);
        stuAnswers.add(stuAnswer16);
        stuAnswers.add(stuAnswer17);
        stuAnswers.add(stuAnswer18);
        stuAnswers.add(stuAnswer19);
        stuAnswers.add(stuAnswer20);
        stuAnswers.add(stuAnswer21);
        stuAnswers.add(stuAnswer22);
        stuAnswers.add(stuAnswer23);
        stuAnswers.add(stuAnswer24);
        stuAnswers.add(stuAnswer25);
        stuAnswers.add(stuAnswer26);
        stuAnswers.add(stuAnswer27);
        stuAnswers.add(stuAnswer28);
        stuAnswers.add(stuAnswer29);
        stuAnswers.add(stuAnswer30);
        stuAnswers.add(stuAnswer31);
        stuAnswers.add(stuAnswer32);
        stuAnswers.add(stuAnswer33);
        stuAnswers.add(stuAnswer34);
        stuAnswers.add(stuAnswer35);

        answers.add(answer1);
        answers.add(answer2);
        answers.add(answer3);
        answers.add(answer4);
        answers.add(answer5);
        answers.add(answer6);
        answers.add(answer7);
        answers.add(answer8);
        answers.add(answer9);
        answers.add(answer10);
        answers.add(answer11);
        answers.add(answer12);
        answers.add(answer13);
        answers.add(answer14);
        answers.add(answer15);
        answers.add(answer16);
        answers.add(answer17);
        answers.add(answer18);
        answers.add(answer19);
        answers.add(answer20);
        answers.add(answer21);
        answers.add(answer22);
        answers.add(answer23);
        answers.add(answer24);
        answers.add(answer25);
        answers.add(answer26);
        answers.add(answer27);
        answers.add(answer28);
        answers.add(answer29);
        answers.add(answer30);
        answers.add(answer31);
        answers.add(answer32);
        answers.add(answer33);
        answers.add(answer34);
        answers.add(answer35);
        TotalScore totalScore=new TotalScore();
        double sum=totalScore.ComputeTotalScore("10086","liulihua",stuAnswers,answers);
        System.out.println(sum);

    }
}
